server:
  port: 8765

spring:
  application:
    name: gateway-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
      
zuul:
  routes:
    employee:
      path: /employees/**
      serviceId: employee-service
      strip-prefix: false
    reimbursementrequest:
      path: /requests/**
      strip-prefix: false
      serviceId: request-service