--2.1 SELECT

SELECT * FROM CHINOOK.EMPLOYEE;

SELECT * FROM CHINOOK.EMPLOYEE
    WHERE LASTNAME = 'King';

SELECT * FROM CHINOOK.EMPLOYEE
    WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;
    
--2.2 ORDER BY
SELECT * FROM CHINOOK.ALBUM
    ORDER BY TITLE;
    
SELECT FIRSTNAME, CITY FROM CHINOOK.CUSTOMER
    ORDER BY CITY;
    
--2.3 INSERT INTO
SELECT * FROM CHINOOK.CUSTOMER;
INSERT INTO CHINOOK.GENRE (GENREID, NAME) VALUES ('26','Action');
INSERT INTO CHINOOK.GENRE (GENREID, NAME) VALUES ('27','History');

INSERT INTO CHINOOK.EMPLOYEE (EMPLOYEEID, LASTNAME, FIRSTNAME) VALUES ('9','WILLIAM','MARTIN');
INSERT INTO CHINOOK.EMPLOYEE (EMPLOYEEID, LASTNAME, FIRSTNAME) VALUES ('10', 'SMITH', 'MICHAEL');

INSERT INTO CHINOOK.CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME,EMAIL) VALUES ('60','Harrison','Ford','harrisonf@revature.com');
INSERT INTO CHINOOK.CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME,EMAIL) VALUES ('61', 'Stanley','Rogers','stanleyr.@revature.com');

--2.4 UPDATE
SELECT * FROM CHINOOK.CUSTOMER;
UPDATE CHINOOK.CUSTOMER
SET FIRSTNAME = 'Robert', LASTNAME = 'Walter'
WHERE FIRSTNAME = 'Aaron'AND LASTNAME = 'Mitchell'; 

SELECT * FROM CHINOOK.ARTIST;
UPDATE CHINOOK.ARTIST
SET NAME = 'CCR'
WHERE NAME = 'Creedence Clearwater Revival';

--2.5 LIKE
SELECT * FROM CHINOOK.INVOICE;
SELECT * FROM CHINOOK.INVOICE
WHERE BILLINGADDRESS LIKE 'T%'; 

--2.6 BETWEEN
SELECT *
FROM CHINOOK.INVOICE
WHERE TOTAL BETWEEN 15 AND 50; 

SELECT *
FROM CHINOOK.INVOICE
WHERE INVOICEDATE BETWEEN DATE '2003-06-01' AND DATE '2004-01-01'; 

--2.7 DELETE
SELECT * FROM CUSTOMER;
DELETE FROM CUSTOMER
WHERE NAME = 'Robert Walter';

--3.1 USER DEFINED FUNCTIONS
CREATE OR REPLACE FUNCTION RETURN_TIME
RETURN VARCHAR2
IS
BEGIN
    RETURN TO_CHAR(CURRENT_TIMESTAMP, 'HH:MI:SS');
END;
/
BEGIN
    DBMS_OUTPUT.PUT_LINE(RETURN_TIME());
END;

CREATE OR REPLACE FUNCTION RETURN_LENGTH(X IN VARCHAR2)
RETURN NUMBER
IS
BEGIN
    RETURN(LENGTH(SELECT NAME FROM CHINOOK.MEDIATYPE WHERE NAME = X));
END;

BEGIN
    LENGTH('MPEG audio file');
END;

LENGTH(SELECT NAME FROM CHINOOK.MEDIATYPE WHERE NAME = 'MPEG audio file');
SELECT LENGTH('CANDIDE') "Length in characters"
   FROM DUAL;


--3.2 SYSTEM DEFINED AGGREGATE FUNCTIONS
CREATE OR REPLACE FUNCTION AVERAGE_TOTAL
RETURN NUMBER
IS
Y NUMBER
BEGIN
    --RETURN 
    SET  Y = (SELECT AVG(TOTAL) FROM CHINOOK.INVOICE);
    RETURN Y;
END; 
/

--7.1 INNER
SELECT *
FROM CHINOOK.CUSTOMER
INNER JOIN CHINOOK.INVOICE ON CHINOOK.CUSTOMER.CUSTOMERID = CHINOOK.INVOICE.CUSTOMERID; 

--7.2 OUTER
SELECT CHINOOK.INVOICE.CUSTOMERID, CHINOOK.CUSTOMER.FIRSTNAME, CHINOOK.CUSTOMER.LASTNAME, CHINOOK.INVOICE.INVOICEID, TOTAL
FROM CHINOOK.CUSTOMER
FULL JOIN CHINOOK.INVOICE ON CHINOOK.CUSTOMER.CUSTOMERID = CHINOOK.INVOICE.CUSTOMERID; 

--7.3 RIGHT
SELECT CHINOOK.ARTIST.NAME, CHINOOK.ALBUM.TITLE
FROM CHINOOK.ALBUM
RIGHT JOIN CHINOOK.ARTIST ON CHINOOK.ALBUM.ARTISTID = CHINOOK.ARTIST.ARTISTID; 


--7.4 CROSS
SELECT CHINOOK.ARTIST.NAME, CHINOOK.ALBUM.TITLE
FROM CHINOOK.ALBUM
CROSS JOIN CHINOOK.ARTIST;


--7.5 SELF
SELECT *
FROM CHINOOK.EMPLOYEE
WHERE REPORTSTO = 2; 