CREATE TABLE ACCOUNT(
    ID NUMBER(5) CONSTRAINT PK_ID PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL);

ALTER TABLE PROFILE MODIFY ID NUMBER(5) NOT NULL;

SELECT * FROM JGONZD.Customer;

SELECT * FROM RECEIPT;

COMMIT;

SELECT * FROM ACCOUNT;

CREATE TABLE PROFILE(
    ID NUMBER(5) CONSTRAINT FK_ID REFERENCES ACCOUNT,
    STREET VARCHAR2(50),
    CITY VARCHAR2(50),
    STATE VARCHAR2(50),
    COUNTRY VARCHAR2(50),
    PHONE NUMBER(11),
    HIREDATE DATE,
    BIRTHDATE DATE
);



ALTER TABLE PROFILE ADD ZIPCODE NUMBER(5);

ALTER TABLE RECEIPT ADD RESOLVEDBY VARCHAR2(50);
ALTER TABLE RECEIPT ADD OUTCOME VARCHAR2(50);

COMMIT;

ALTER TABLE PROFILE
DROP COLUMN ROLE;

SELECT * FROM PROFILE;
SELECT * FROM ACCOUNT;



ALTER TABLE PROFILE ADD EMAIL VARCHAR2(50);

ALTER TABLE PROFILE ADD FNAME VARCHAR2(50);
ALTER TABLE PROFILE ADD LNAME VARCHAR2(50);

ALTER TABLE RECEIPT ADD CONSTRAINT PK_RID PRIMARY KEY (RID);

SELECT * FROM PROFILE;

CREATE TABLE RECEIPT(
    RID NUMBER(5) CONSTRAINT PK_RID PRIMARY KEY,
    STATUS VARCHAR2(50),
    DETAILS VARCHAR2(50),
    AMOUNT NUMBER(7,2),
    PURCHASEDATE DATE,
    STATUSDATE DATE
);

ALTER TABLE RECEIPT ADD PURCHASEDATE VARCHAR2(50);
ALTER TABLE RECEIPT ADD STATUSDATE VARCHAR2(50);

INSERT INTO RECEIPT (ID, RID, STATUS, AMOUNT, DETAILS, PURCHASEDATE, STATUSDATE) VALUES (1,1,'PENDING', 205.00, 'Work Laptop', DATE '2018-09-01', DATE '2018-09-08');

ALTER TABLE RECEIPT
DROP CONSTRAINT PK_RID;

COMMIT;

DELETE FROM RECEIPT WHERE ID = 2;

SELECT * FROM RECEIPT;

UPDATE ACCOUNT
SET ROLE = 0
WHERE ID = 2;
UPDATE ACCOUNT
SET ROLE = 0
WHERE ID = 2;
UPDATE ACCOUNT
SET ROLE = 0
WHERE ID = 3;
UPDATE ACCOUNT
SET ROLE = 0
WHERE ID = 4;
UPDATE ACCOUNT
SET ROLE = 0
WHERE ID = 5;
UPDATE ACCOUNT
SET ROLE = 0
WHERE ID = 6;
UPDATE ACCOUNT
SET ROLE = 0
WHERE ID = 7;
UPDATE ACCOUNT
SET ROLE = 0
WHERE ID = 8;
UPDATE ACCOUNT
SET ROLE = 0
WHERE ID = 9;
UPDATE ACCOUNT
SET ROLE = 0
WHERE ID = 10;
UPDATE ACCOUNT
SET ROLE = 1
WHERE ID = 5;

SELECT * FROM ACCOUNT;
SELECT * FROM RECEIPT;

COMMIT;

SELECT * FROM ACCOUNT;

COMMIT;

SELECT COUNT(RID) FROM RECEIPT;

DELETE FROM RECEIPT WHERE RID = 6;

select * from v$lock where type = ‘TM’ and lmode = 6;
select * from V$SESSION_ID where SID = 44;
select * from v$locked_object;
select * from v$44;

select 
   sid,
   serial#
from 
   v$session;

alter system kill session '44,20532';

begin
    rdsadmin.rdsadmin_util.kill(
        sid    => 47, 
        serial => 60955);
end;
/

select 
   session_id
from 
   v$lock
where 
   name = 'EMP';

SELECT * FROM PROFILE;

INSERT INTO RECEIPT (ID, RID, STATUS, AMOUNT, DETAILS, PURCHASEDATE, STATUSDATE) VALUES (1,2,'PENDING', 8.65, 'Travel', DATE '2018-09-03', DATE '2018-09-03');
INSERT INTO RECEIPT (ID, RID, STATUS, AMOUNT, DETAILS, PURCHASEDATE, STATUSDATE) VALUES (1,3,'PENDING', 11.19, 'Miscellaneous Tools', DATE '2018-09-04', DATE '2018-09-04');
INSERT INTO RECEIPT (ID, RID, STATUS, AMOUNT, DETAILS, PURCHASEDATE, STATUSDATE) VALUES (1,4,'RESOLVED', 44.23, 'Parking permit', DATE '2018-09-05', DATE '2018-09-07');
INSERT INTO RECEIPT (ID, RID, STATUS, AMOUNT, DETAILS, PURCHASEDATE, STATUSDATE) VALUES (1,5,'RESOLVED', 123.43, 'Car Rental', DATE '2018-09-05', DATE '2018-09-08');

INSERT INTO RECEIPT (ID, RID, STATUS, AMOUNT, DETAILS, PURCHASEDATE, STATUSDATE) VALUES (2,1,'RESOLVED', 13.43, 'Train Fare', DATE '2018-09-05', DATE '2018-09-08');

INSERT INTO RECEIPT (ID, RID, STATUS, AMOUNT, DETAILS, PURCHASEDATE) VALUES (2,11,'RESOLVED', 13.43, 'Train Fare', DATE '2018-09-05');

INSERT INTO RECEIPT (ID, RID, STATUS, AMOUNT, DETAILS, PURCHASEDATE) VALUES (2,12,'PENDING', 8.90, 'Bus Fare', DATE '2018-09-05');


Commit;

SELECT * FROM (SELECT * FROM ACCOUNT INNER JOIN RECEIPT ON ACCOUNT.ID = RECEIPT.ID) WHERE ID = 1;
SELECT * FROM ACCOUNT WHERE ID = 1;

insert into ACCOUNT (ID, USERNAME, PASSWORD) values (1, 'user', 'password');

SELECT * FROM ACCOUNT;

SELECT * FROM ACCOUNT WHERE USERNAME = 'user' AND PASSWORD = 'password';

SELECT * FROM ACCOUNT WHERE USERNAME = 'user' AND PASSWORD = 'password';

DROP TABLE USERS;

ALTER TABLE USERS ADD ID NUMBER(5);

ALTER TABLE RECEIPT ADD ID NUMBER(5) CONSTRAINT FK_ID_R REFERENCES ACCOUNT NOT NULL;

SELECT * FROM PROFILE WHERE ID = 1;

COMMIT;

ALTER TABLE ACCOUNT
ADD ROLE NUMBER(1);

COMMIT;

SELECT * FROM ACCOUNT;

insert into ACCOUNT (ID, USERNAME, PASSWORD) values (1, 'user', 'password');
insert into ACCOUNT (ID, USERNAME, PASSWORD) values (2, 'awardlaw1', 'F1kefQZz6XLE');
insert into ACCOUNT (ID, USERNAME, PASSWORD) values (3, 'tknott2', 'o3vNpfrVCNx2');
insert into ACCOUNT (ID, USERNAME, PASSWORD) values (4, 'dhayles3', 'Wg5XfoUOatr');
insert into ACCOUNT (ID, USERNAME, PASSWORD) values (5, 'docarmody4', 'rTco7LV');
insert into ACCOUNT (ID, USERNAME, PASSWORD) values (6, 'rblethyn5', 'r9QcAvWGFynM');
insert into ACCOUNT (ID, USERNAME, PASSWORD) values (7, 'jmidlar6', '3hddWw25xg');
insert into ACCOUNT (ID, USERNAME, PASSWORD) values (8, 'jvedeniktov7', 'UWDKLttgfXzE');
insert into ACCOUNT (ID, USERNAME, PASSWORD) values (9, 'ibeminster8', 'dtXvtUweykS');
insert into ACCOUNT (ID, USERNAME, PASSWORD) values (10, 'soakinfold9', 'skvGXUJ0');

insert into PROFILE (ID, STREET, CITY, STATE, FNAME, LNAME, PHONE, HIREDATE, BIRTHDATE, ZIPCODE, EMAIL) values (1, '9 Saint Paul Point', 'Des Moines', 'Iowa', 'Maxine', 'Langthorne', '5157908941', '2017-09-15', '1988-01-14', '50310', 'mlangthorne0@wordpress.org');
insert into PROFILE (ID, STREET, CITY, STATE, FNAME, LNAME, PHONE, HIREDATE, BIRTHDATE, ZIPCODE, EMAIL) values (2, '52 Russell Park', 'Jamaica', 'New York', 'Concordia', 'Gozzard', '7182652790', '2018-03-23', '1992-04-02', '11480', 'cgozzard1@google.ca');
insert into PROFILE (ID, STREET, CITY, STATE, FNAME, LNAME, PHONE, HIREDATE, BIRTHDATE, ZIPCODE, EMAIL) values (3, '042 Hoard Hill', 'Louisville', 'Kentucky', 'Martguerita', 'Hasslocher', '5024900718',  '2018-06-24', '1998-01-02', '40298', 'mhasslocher2@hp.com');
insert into PROFILE (ID, STREET, CITY, STATE, FNAME, LNAME, PHONE, HIREDATE, BIRTHDATE, ZIPCODE, EMAIL) values (4, '9 Duke Lane', 'Henderson', 'Nevada', 'Brina', 'Vannini', '7025267578', '2017-10-05', '1986-09-05', '89012', 'bvannini3@soundcloud.com');
insert into PROFILE (ID, STREET, CITY, STATE, FNAME, LNAME, PHONE, HIREDATE, BIRTHDATE, ZIPCODE, EMAIL) values (5, '44 Independence Center', 'Lima', 'Ohio', 'Kylila', 'Brien', '4198547288', '2018-03-11', '1982-05-30', '45807', 'kbrien4@mapquest.com');
insert into PROFILE (ID, STREET, CITY, STATE, FNAME, LNAME, PHONE, HIREDATE, BIRTHDATE, ZIPCODE, EMAIL) values (6, '727 Jenifer Road', 'Charlotte', 'North Carolina', 'Michal', 'Dorsett', '7047824778', '2017-10-20', '1987-01-27', '28215', 'mdorsett5@nps.gov');
insert into PROFILE (ID, STREET, CITY, STATE, FNAME, LNAME, PHONE, HIREDATE, BIRTHDATE, ZIPCODE, EMAIL) values (7, '0421 Maywood Plaza', 'Portland', 'Oregon', 'Belia', 'Ledes', '5038190370', '2017-09-26', '1986-09-04', '97206', 'bledes6@aol.com');
insert into PROFILE (ID, STREET, CITY, STATE, FNAME, LNAME, PHONE, HIREDATE, BIRTHDATE, ZIPCODE, EMAIL) values (8, '57 Havey Park', 'Saint Joseph', 'Missouri', 'Jordain', 'Jadczak', '8163154119', '2017-11-07', '1983-02-11', '64504', 'jjadczak7@acquirethisname.com');
insert into PROFILE (ID, STREET, CITY, STATE, FNAME, LNAME, PHONE, HIREDATE, BIRTHDATE, ZIPCODE, EMAIL) values (9, '59 Dayton Hill', 'Fullerton', 'California', 'Mariquilla', 'Kendle', '5593168898', '2018-07-07', '1989-01-20', '92640', 'mkendle8@ustream.tv');
insert into PROFILE (ID, STREET, CITY, STATE, FNAME, LNAME, PHONE, HIREDATE, BIRTHDATE, ZIPCODE, EMAIL) values (10, '6 Hagan Avenue', 'Longview', 'Texas', 'Van', 'Pischof', '9038727206', '2018-08-08', '1983-09-28', '75605', 'vpischof9@irs.gov');

SELECT * FROM PROFILE;

COMMIT;

ALTER TABLE PROFILE
ADD HIREDATE VARCHAR(50);

TRUNCATE TABLE PROFILE;

