-- CREATION

CREATE TABLE BANK (
    BANK_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    AMOUNT NUMBER(10, 2),
    USER_ID NUMBER
);

CREATE TABLE USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL primary key,
    USERNAME VARCHAR2(15) UNIQUE NOT NULL,
    USER_EMAIL VARCHAR2(40) UNIQUE NOT NULL,
    USER_PASSWORD VARCHAR2(20) NOT NULL
);

ALTER TABLE BANK
ADD CONSTRAINT FK_BANK_USER
FOREIGN KEY (USER_ID) REFERENCES USERS ON DELETE CASCADE;

ALTER TABLE BANK 
MODIFY 
    (AMOUNT NUMBER(10, 2) DEFAULT 0
);

ALTER TABLE BANK
MODIFY (
    USER_ID NUMBER
);

alter table users 
add column (user_password varchar2(20) not null);

ALTER TABLE BANK
ROW ARCHIVAL;

ALTER TABLE USERS
ADD DATE_CREATED DATE;

ALTER TABLE USERS
ROW ARCHIVAL;