-- CREATION

CREATE TABLE BANK (
    BANK_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    AMOUNT NUMBER(10, 2),
    USER_ID NUMBER
);

CREATE TABLE USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) primary key,
    USERNAME VARCHAR2(15) UNIQUE NOT NULL,
    USER_EMAIL VARCHAR2(40) UNIQUE NOT NULL,
    USER_PASSWORD VARCHAR2(20) NOT NULL
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) primary key,
    USER_ID NUMBER,
    TRANSACTION_TYPE VARCHAR(15) NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL 
);



ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_USER_TRAN
FOREIGN KEY (USER_ID) REFERENCES USERS;

ALTER TABLE TRANSACTIONS
ADD (FROM_USER_ID NUMBER);

ALTER TABLE BANK
ADD CONSTRAINT FK_BANK_USER
FOREIGN KEY (USER_ID) REFERENCES USERS ON DELETE CASCADE;

ALTER TABLE BANK 
MODIFY 
    (
    AMOUNT NUMBER(10, 2) DEFAULT 0
);

ALTER TABLE BANK
MODIFY (
    USER_ID NUMBER
);

ALTER TABLE BANK
ROW ARCHIVAL;

ALTER TABLE USERS
ADD DATE_CREATED DATE;

ALTER TABLE USERS
ROW ARCHIVAL;