
CREATE TABLE USERS(
    
    USERNAME VARCHAR2(50) CONSTRAINT PK_USERNAME PRIMARY KEY, --PRIM KEY
    EMAIL VARCHAR2(100),
    PASSWORD VARCHAR2(100),
    BALANCE NUMBER(10, 2)
);

CREATE TABLE EMAIL_TO_USERNAME (
    EMAIL VARCHAR2(100),
    USERNAME VARCHAR2(50)
);

ALTER TABLE EMAIL_TO_USERNAME
    ADD CONSTRAINT FK_EMAIL_TO_ACCOUNT
    FOREIGN KEY (USERNAME) REFERENCES USERS;
    
COMMIT;


--this is just to make some tests
INSERT INTO USERS VALUES('Cindy', 'clpeng', 'happy4', 50);

--TO START OVER ON YOUR USERS TABLE
DROP TABLE EMAIL_TO_USERNAME;
TRUNCATE TABLE USERS;



CREATE OR REPLACE PROCEDURE DECREASE_BALANCE (USER IN USERS.USERNAME%TYPE, 
        VAL IN USERS.BALANCE%TYPE)
        --THESE WILL ENSURE TYPE SAFETY
IS
BEGIN
    UPDATE USERS
    SET BALANCE = BALANCE - VAL
    WHERE USERNAME = USER;       --VAL AND DEPT COME FROM FIRST LINE OF SP...LN 160
END;
/
