-- we can create a comment like this
/*
this is a multiline comment
we can comment on this line too
*/

-------------------------------------
-- USING DDL TO CREATE OUR TABLES
-------------------------------------
CREATE TABLE DEPARTMENT(
    DEPT_ID NUMBER(5) CONSTRAINT PK_DEPT PRIMARY KEY,
    DEPT_NAME VARCHAR2(50),
    MONTHLY_BUDGET NUMBER(7,2)
);

CREATE TABLE EMPLOYEE (
    EMP_ID NUMBER(5) CONSTRAINT PK_EMP PRIMARY KEY,
    EMP_NAME VARCHAR2(50),
    BIRTHDAY DATE,
    MONTHLY_SALARY NUMBER(7,2) NOT NULL,
    HIRE_DATE DATE,
    POSITION VARCHAR2(20),
    MANAGER_ID NUMBER(5),
    DEPT_ID NUMBER(5) CONSTRAINT FK_EMP_DPT REFERENCES DEPARTMENT
);

-- We can't first insert to our employee table with a department without first defining the department
-- INSERT INTO EMPLOYEE VALUES (1, 'JOHN SMITH', DATE '1989-01-05', 2000, DATE '2015-03-08', 'MK_REP',NULL,1);

-- INSERTING RECORDS INTO OUR DEPARTMENT TABLE
INSERT INTO DEPARTMENT VALUES (1, 'MARKETING', 5000);
INSERT INTO DEPARTMENT VALUES (2, 'ACCOUNTING', 4000);
INSERT INTO DEPARTMENT VALUES (3, 'INFORMATION TECHNOLOGY', 4500);
INSERT INTO DEPARTMENT VALUES (4, 'HUMAN RESOURCED', 3500);
INSERT INTO DEPARTMENT VALUES (5, 'LEGAL', 2000);
INSERT INTO DEPARTMENT VALUES (6, 'CUSTOMER SERVICE', 3000);
-- INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (7, 'SALES'); 

-- WHEN ATTEMPTING TO DROP A TABLE WHICH IS REFERENCED BY ANOTHER WE ARE UNABLE TO DO SO
DROP TABLE DEPARTMENT;

-- WE ARE ABLE TO DROP THE TABLE ONCE THE RELATIONSHIP IS REMOVED
ALTER TABLE EMPLOYEE 
DROP CONSTRAINT FK_EMP_DPT;

-- DROP TABLE DEPARTMENT;

-- RE-CREATING OUR FOREIGN KEY RELATIONSHIP 
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMP_DPT
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID) ON DELETE CASCADE;
-- ANOTHER OPTION HERE IS 'ON DELETE SET NULL' 

-- INSERT SOME EMPLOYEES INTO OUR EMPLOYEE TABLE (DML)
INSERT INTO EMPLOYEE VALUES (1, 'JOHN SMITH', DATE '1989-01-05', 2000, DATE '2015-03-08', 'MK_REP',NULL,1);
INSERT INTO EMPLOYEE VALUES (2, 'JAMES BOSH', DATE '1990-08-13', 3200, DATE '2013-02-20', 'AC_ACCOUNT',NULL,2);
INSERT INTO EMPLOYEE VALUES (3, 'LISA JACKSON', DATE '1988-10-15', 3800, DATE '2012-03-08', 'IT_PROF',NULL,3);
INSERT INTO EMPLOYEE VALUES (4, 'ANGELA DEAN', DATE '1982-12-07', 2000, DATE '2017-04-12', 'IT_PROF',3,3);
INSERT INTO EMPLOYEE VALUES (5, 'NIGEL OAKS', DATE '1990-07-28', 2200, DATE '2018-07-20', 'MK_REP',1,1);
INSERT INTO EMPLOYEE VALUES (6, 'JAMES BOND', DATE '1992-11-13', 2800, DATE '2017-10-03', 'MK_REP',1,1);

SELECT EMP_NAME
FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE;

DELETE FROM EMPLOYEE
WHERE MONTHLY_SALARY>3500;

DELETE FROM EMPLOYEE
WHERE EMP_ID=3;

------------------------------------
-- QUERYING THE DATABASE
------------------------------------

SELECT * 
FROM EMPLOYEE 
WHERE MANAGER_ID=1;

SELECT EMP_NAME, MONTHLY_SALARY, HIRE_DATE
FROM EMPLOYEE 
WHERE MANAGER_ID=1;

SELECT *
FROM EMPLOYEE 
WHERE EMP_NAME LIKE 'JAMES%'
ORDER BY MONTHLY_SALARY DESC;

SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE;

-- SHOW THE AVERAGE SALARY BY DEPARTMENT
SELECT DEPT_ID DEPT, ROUND(AVG(MONTHLY_SALARY)) AVG_SALARY
FROM EMPLOYEE
GROUP BY DEPT_ID
HAVING DEPT_ID<3;
