----------------------------------------Tuesday
--ANSWER E
SELECT * FROM INVOICE
WHERE INVOICE_DATE = DATE '2018-08-21';

--ANSWER F
SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID)
FROM INVOICE
GROUP BY CUSTOMER_ID;

--ANSWER G
SELECT CUSTOMER_ID, SUM(INVOICE_AMOUNT)
FROM INVOICE
GROUP BY CUSTOMER_ID;

-ANSWER H
SELECT * FROM INVOICE
WHERE EXTRACT(MONTH FROM INVOICE_DATE)=8 AND EXTRACT(YEAR FROM INVOICE_DATE)=2018
ORDER BY INVOICE_AMOUNT DESC;

-ANSWER I
SELECT *
FROM ( SELECT *
        FROM INVOICE
        ORDER BY INVOICE_AMOUNT DESC
    )
WHERE ROWNUM <= 3 AND INVOICE_ID IS NOT NULL;
------------------------------------------------------------------------------------

----------------------Wednesday--------------------------------------------

ANSWER A
-----------
SELECT * FROM INVOICE
WHERE CUSTOMER_ID IS NOT NULL AND INVOICE_ID IS NOT NULL;

ANSWER B
-------------
SELECT * FROM INVOICE
WHERE CUSTOMER_ID IS NOT NULL;

ANSWER C
--------------
SELECT *
FROM INVOICE
LEFT JOIN CUSTOMER ON INVOICE.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID; 

ANSWER D
-------------
SELECT NAME, SUM(INVOICE_AMOUNT)
FROM (SELECT * FROM INVOICE
RIGHT JOIN CUSTOMER ON INVOICE.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID)
GROUP BY NAME;

ANSWER E
---------------
SELECT *
FROM ( SELECT *
        FROM INVOICE
        ORDER BY INVOICE_DATE DESC
    )
WHERE ROWNUM = 1 AND INVOICE_ID IS NOT NULL;

ANSWER F
----------------
SELECT INVOICE_ID, NAME, 1.06*INVOICE_AMOUNT
FROM (SELECT * FROM INVOICE
RIGHT JOIN CUSTOMER ON INVOICE.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID);