--A
SELECT DISTINCT I.INV_ID AS INVOICE,
C.CUST_NAME AS CUSTOMER
FROM INVOICE I
INNER JOIN  CUSTOMER C
ON C.CUST_ID = C.CUST_ID;
--B
SELECT DISTINCT C.CUST_NAME AS NAME,
I.INV_ID AS INVOICE
FROM CUSTOMER C
LEFT OUTER JOIN INVOICE I
ON C.CUST_ID = C.CUST_ID;
--C
SELECT *
FROM INVOICE
FULL OUTER JOIN CUSTOMER ON CUSTOMER.CUST_ID = CUSTOMER.CUST_ID;
--D
SELECT C.CUST_NAME, SUM(I.INV_AMT) TOTALAMOUNT
FROM INVOICE I
JOIN CUSTOMER C ON
C.CUST_ID=I.INV_ID
GROUP BY C.CUST_NAME
ORDER BY TOTALAMOUNT;

--E
SELECT * 
FROM (SELECT * FROM CUSTOMER C
LEFT JOIN INVOICE I
ON C.CUST_ID = C.CUST_ID
ORDER  BY INV_DATE DESC)
WHERE ROWNUM<=1;
--F
SELECT  C.CUST_NAME AS NAME, 
(SUM(I.INV_AMT)-(SUM(I.INV_AMT)*.06)) SUBTOTAL
         
    FROM CUSTOMER C
    LEFT JOIN INVOICE I
    ON I.INV_ID = C.CUST_ID
    GROUP BY C.CUST_NAME;
