CREATE TABLE BANK_USERS(
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    USERNAME VARCHAR2(20) UNIQUE NOT NULL,
    EMAIL VARCHAR2(30) UNIQUE NOT NULL,
    USER_PASSWORD VARCHAR2 (30) NOT NULL
);

CREATE TABLE BANK(
    ACCOUNT_NO NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    BALANCE NUMBER(10, 2) DEFAULT 0,
    USER_ID NUMBER(10)
);

CREATE OR REPLACE PROCEDURE DEPOSIT(ACCT IN BANK.ACCOUNT_NO%TYPE, VAL IN BANK.BALANCE%TYPE)
IS
BEGIN
    UPDATE BANK
    SET BALANCE = BALANCE + VAL
    WHERE ACCOUNT_NO = ACCT;
END;

CREATE OR REPLACE PROCEDURE WITHDRAW(ACCT IN BANK.ACCOUNT_NO%TYPE, VAL IN BANK.BALANCE%TYPE)
IS
BEGIN
    UPDATE BANK
    SET BALANCE = BALANCE - VAL
    WHERE ACCOUNT_NO = ACCT;
END;

UPDATE BANK
SET BALANCE = BALANCE + 500
WHERE account_no = 1;

ALTER TABLE BANK
ADD CONSTRAINT FK_BANK_USER
FOREIGN KEY (USER_ID) REFERENCES BANK_USERS ON DELETE CASCADE;


ALTER TABLE BANK_USERS
ROW ARCHIVAL;
