server:
  port: 8765
  
spring:
  application:
    name: gateway-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    account:
      path: /employee/**
      serviceId: employee-service
      strip-prefix: false
    customer:
      path: /reimbursement/**
      serviceId: reimbursement-service
      strip-prefix: false
      