
#Sets the port number to run this service on
server:
  port: 8761

#Configuration settings for Eureka Discovery Service. 
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false