server:
  port: 2333
  
spring:
  application:
    name: reimbursement-service  
  
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30
