CREATE TABLE BANK_USER (
    USER_NAME VARCHAR2(255) CONSTRAINT PK_USER PRIMARY KEY,
    FNAME VARCHAR2(20),
    LNAME VARCHAR2(20),
    PSWD VARCHAR(255)
);
CREATE TABLE ACCOUNT (
 ACCOUNT_NUMBER NUMBER(15) CONSTRAINT PK_ACC PRIMARY KEY,
 BALLANCE DECIMAL(6, 2),
 USER_NAME VARCHAR2(255) CONSTRAINT FK_BUSER_NAME REFERENCES BANK_USER ON DELETE CASCADE
);


CREATE SEQUENCE SQ_BANK_ACC
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_INSERT_BANK_ACC
BEFORE INSERT ON ACCOUNT
FOR EACH ROW
BEGIN
    SELECT SQ_BANK_ACC.NEXTVAL INTO :NEW.ACCOUNT_NUMBER FROM DUAL;
END;
/


CREATE OR REPLACE PROCEDURE DELETE_USERANDACC(USER_NAME IN VARCHAR2)
IS
BEGIN
    DELETE FROM BANK_USER WHERE BANK_USER.USER_NAME = USER_NAME; 
END;
/
commit;
insert into bank_user (User_name, fname, lname, pswd) values ('Larry001', 'larry', 'larry', 'larry');
insert into bank_user (User_name, fname, lname, pswd) values ('Gimly', 'Gimly', 'Dwarf', 'gimlyrules');
insert into account (user_name, ballance) values ('Larry001', 100.25);
insert into account (user_name, ballance) values ('Gimly', 100.25);
commit;