---------------------
-- TCL
---------------------

COMMIT;

SELECT STREET STREE1, CITY CITY1, STATE STATE1
FROM LOCATIONS;

SAVEPOINT SP1;

UPDATE LOCATIONS
SET CITY = 'KANSAS CITY';

SELECT STREET STREET2, CITY CITY2, STATE STATE2
FROM LOCATIONS;

ROLLBACK TO SP1;

UPDATE LOCATIONS
SET CITY = 'OKLAHOMA CITY'
WHERE LOCATION_ID = 3;

SELECT STREET STREET2, CITY CITY3, STATE STATE3
FROM LOCATIONS;

ROLLBACK;
COMMIT;

SELECT STREET STREET4, CITY CITY4, STATE STATE4
FROM LOCATIONS;
