
CREATE TABLE USERS(
    U_ID NUMBER PRIMARY KEY,
    U_USERNAME VARCHAR2(100),
    U_PASSWORD VARCHAR2(100),
    U_FIRSTNAME VARCHAR2(60),
    U_LASTNAME VARCHAR2(60),
    U_EMAIL VARCHAR2(100),
    UR_ID NUMBER CONSTRAINT FK_R_ID REFERENCES REIMBURSEMENTS
);

SELECT * FROM USERS WHERE U_USERNAME = 'AJ1' AND U_PASSWORD = 'AJ1';


CREATE TABLE REIMBURSEMENTS(
    R_ID NUMBER PRIMARY KEY,
    R_AMOUNT NUMBER,
    R_DESCRIPTION VARCHAR2(100),
    R_RECEIPT BLOB,
    R_SUBMITTED TIMESTAMP,
    R_RESOLVED TIMESTAMP,
    U_ID_AUTHOR NUMBER,
    U_ID_RESOLVER NUMBER,
    RT_TYPE NUMBER,
    RT_STATUS NUMBER
);
INSERT INTO USERS VALUES(1, 'AJ1', 'AJ1', 'Awkward', 'Jogger', 'aj@cnn.com', 50);
INSERT INTO REIMBURSEMENTS VALUES(50, 1000, 'Bribe to leave Revature', '54455354', '21-OCT-13', '21-OCT-13', 50, 50, 50, 50);

CREATE OR REPLACE PROCEDURE PR_CREATE_REIMB(RID IN REIMBURSEMENTS.R_ID%TYPE,
UID IN USERS.U_ID%TYPE, status IN REIMBURSEMENTS.RT_STATUS)
IS 
BEGIN
    INSERT INTO REIMBURSEMENTS VALUES();
   
END;

CREATE OR REPLACE PROCEDURE PR_APPROVE_REIMB(RID IN REIMBURSEMENTS.R_ID%TYPE,
UID IN USERS.U_ID%TYPE, status IN REIMBURSEMENTS.RT_STATUS)
IS 
BEGIN
    UPDATE REIMBURSEMENTS
    SET
    WHERE USERNAME = CUST;
END;
/

Select * from reimbursements;

SELECT * FROM USERS WHERE U_USERNAME = 'AJ1' AND U_PASSWORD = 'AJ1';