server:
  port: 2333
  
spring:
  application:
    name: reimbursement-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2