server:
  port: 5555
  
spring:
  application:
    name: gateway-server
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    account:
      path: /reimbursements/**
      serviceId: reimbursement-service
      strip-prefix: false
    customer:
      path: /employees/**
      serviceId: employee-service
      strip-prefix: false