server:
  port: 3333

spring:
  application:
    name: employee-service

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    #This part (and the spring application part registers employeeservice with Eureka
#    register-with-eureka: true      #I think this line is done maybe better (more customized, witht the name) through spring.application.name



    
