-- CREATE USER TABLE
CREATE TABLE USERS (
USERNAME VARCHAR2(50) CONSTRAINT PK_USER PRIMARY KEY,
PASSWORD VARCHAR2(50),
BALANCE NUMBER (10,2)
);

INSERT INTO USERS VALUES ('simmonbr','matrix',500);
INSERT INTO USERS VALUES ('revature','codelikeaboss',10000);
commit;

CREATE OR REPLACE PROCEDURE DEPOSIT_AMOUNT(USR IN USERS.USERNAME%TYPE, VAL IN USERS.BALANCE%TYPE)
IS 
BEGIN
    UPDATE USERS
    SET BALANCE = BALANCE + VAL
    WHERE USERNAME = USR;
END;
/

CREATE OR REPLACE PROCEDURE WITHDRAWAL_AMOUNT(USR IN USERS.USERNAME%TYPE, VAL IN USERS.BALANCE%TYPE)
IS 
BEGIN
    UPDATE USERS
    SET BALANCE = BALANCE - VAL
    WHERE USERNAME = USR;
END;
/


