server:
  port: 8765

spring:
  application:
    name: gateway-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    reimbursement:
      path: /reimbursements/**
      serviceId: reimbursement-service
      strip-prefix: false
    employee:
      path: /employeess/**
      serviceId: employee-service
      strip-prefix: false