DROP TABLE LOGIN CASCADE CONSTRAINTS;
DROP TABLE BALANCE CASCADE CONSTRAINTS;

CREATE TABLE LOGIN (
    USERNAME VARCHAR2(30) PRIMARY KEY,
    PASSWORD VARCHAR2(30) NOT NULL
);

CREATE TABLE BALANCE (
    USERNAME VARCHAR2(30),
    BALANCE NUMBER(20, 2) DEFAULT 0,
    CONSTRAINT FK_BAL_LOG
        FOREIGN KEY (USERNAME)
        REFERENCES LOGIN(USERNAME)
        ON DELETE CASCADE
);

INSERT INTO LOGIN VALUES ('user', 'password');
INSERT INTO LOGIN VALUES ('josh.pen', 'kappa123');
INSERT INTO LOGIN VALUES ('user@email.com', 'password');

INSERT INTO BALANCE VALUES ('user', 100.23);
INSERT INTO BALANCE VALUES ('josh.pen', 15.30);
INSERT INTO BALANCE VALUES ('user@email.com', 6000.15);

COMMIT;

CREATE OR REPLACE PROCEDURE GET_BALANCE (ID IN BALANCE.USERNAME%TYPE, MONEY OUT BALANCE.BALANCE%TYPE)
IS
BEGIN
    SELECT B.BALANCE INTO MONEY
    FROM BALANCE B
    WHERE B.USERNAME = ID;
END;
/

CREATE OR REPLACE PROCEDURE SET_BALANCE (ID IN BALANCE.USERNAME%TYPE, MONEY IN BALANCE.BALANCE%TYPE)
IS
BEGIN
    UPDATE BALANCE
    SET BALANCE.BALANCE = MONEY
    WHERE BALANCE.USERNAME = ID;
    COMMIT;
END;
/

SET SERVEROUTPUT ON;

DECLARE
    MONEY BALANCE.BALANCE%TYPE;
BEGIN
    MONEY := 200.03;
    SET_BALANCE('user', MONEY);
    GET_BALANCE('user', MONEY);
    DBMS_OUTPUT.PUT_LINE(MONEY);
END;
/