DROP TABLE LOGIN CASCADE CONSTRAINTS;
DROP TABLE BALANCE CASCADE CONSTRAINTS;

CREATE TABLE LOGIN (
    USERNAME VARCHAR2(30) PRIMARY KEY,
    PASSWORD VARCHAR2(30) NOT NULL
);

CREATE TABLE BALANCE (
    USERNAME VARCHAR2(30),
    BALANCE NUMBER(20, 2) DEFAULT 0,
    CONSTRAINT FK_BAL_LOG
        FOREIGN KEY (USERNAME)
        REFERENCES LOGIN(USERNAME)
        ON DELETE CASCADE
);

INSERT INTO LOGIN VALUES ('user', 'password');
INSERT INTO LOGIN VALUES ('josh.pen', 'kappa123');
INSERT INTO LOGIN VALUES ('user@email.com', 'password');

INSERT INTO BALANCE VALUES ('user', 100.23);
INSERT INTO BALANCE VALUES ('josh.pen', 15.30);
INSERT INTO BALANCE VALUES ('user@email.com', 6000.15);

COMMIT;