server:
  port: 8765
  
spring:
  application:
    name: gateway-server
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    account:
      path: /employees/**
      service-id: employee-service
      strip-prefix: false
    customer:
      path: /reimbursements/**
      service-id: reimbursement-service
      strip-prefix: false