server:
  port: 8765
  
spring:
  application:
    name: gateway-server
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    employee:
      path: /emmployees/**
      serviceId: employee-service
      strip-prefix: false
    reimbursement:
      path: /reimbursements/**
      serviceId: reimbursement-service
      strip-prefix: false